# -*- mode: makefile-gmake; -*-
#*********************************************************************
#
# (C) Copyright Broadcom Corporation 2013-2014
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#*********************************************************************

#path and prefix of toolchain
#
# CROSS_COMPILE setting for GTO boards (Broadcom SVKs)
CROSS_COMPILE_GTO = /projects/nwsoft-toolchains/brl/brl_2.0/brl_2.0.1/gto/bin/powerpc-broadcom-linux-gnu-
# CROSS_COMPILE setting for IM-x86 boards
CROSS_COMPILE_IMx86 =

# Default to GTO cross compile
export CROSS_COMPILE = $(CROSS_COMPILE_GTO)

#directory where the shared library resides
platform := gto-trident-brl20

export AR      = $(CROSS_COMPILE)ar
export AS      = $(CROSS_COMPILE)as
export CC      = $(CROSS_COMPILE)gcc
export LD      = $(CROSS_COMPILE)ld
export NM      = $(CROSS_COMPILE)nm
export OBJCOPY = $(CROSS_COMPILE)objcopy
export OBJDUMP = $(CROSS_COMPILE)objdump
export RANLIB  = $(CROSS_COMPILE)ranlib
export STRIP   = $(CROSS_COMPILE)strip

export SED     = sed
export RM      = rm

export OFDPA_ROOT = ../..

export CFLAGS += -I$(OFDPA_ROOT)/src/include

targets := $(basename $(notdir $(wildcard *.c)))

.PHONY: all dump_vars

all: $(targets)

#
# Build the target executables
# The .o files are built by an implicit rule.
#
$(targets): % : %.o
	$(CC) $(CFLAGS) -o $@ -L$(OFDPA_ROOT)/bin/$(platform) -Wl,-Bstatic $^ -Wl,-Bdynamic -lc -lrpc_client

.SECONDEXPANSION:

#
# This rule builds the dependency files
#
%.d: %.c
	set -e; $(RM) -f $@; \
	$(CC) -MM $(CFLAGS) $< > $@.$$$$; \
	$(SED) 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	$(RM) -f $@.$$$$

-include $(patsubst %.c,%.d,$(notdir $(wildcard *.c)))

dump_vars:
	@echo targets = $(targets)
